---

# Machine Learning via Python:<br> FPO DMG MASD S3

## Prof. Dr. Abdelkrim El Mouatasim

### TP2:  Numpy

---

In [1]:
import numpy as np

# Indexing/Slicing Review

* `s[i]` (indexing)
* `s[i:j]` (slicing)
* `s[i:j:k]` (step slicing)
* meaning of negative indices
* 0-base counting

## EXERCISE: Indexing Review

In [2]:
m = list(range(10)) #in Python3 range returns an iterator! Casting to list is needed
m

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
# access the first position of the list
m[0]
# YOUR CODE HERE

0

In [4]:
# access the last position of the list
# YOUR CODE HERE
m[-1]

9

The triple [i:j:k] are in fact parameters of a **slice** object:

### slice(start, stop[, step])
> Return a slice object representing the set of indices specified by range(start, stop, step). The start and step arguments default to None. Slice objects have read-only data attributes start, stop and step which merely return the argument values (or their default). They have no other explicit functionality; however they are used by Numerical Python and other third party extensions. Slice objects are also generated when extended indexing syntax is used. For example: a[start:stop:step] or a[start:stop, i].

http://docs.python.org/2/library/functions.html#slice

For example, to return the first 3 elements in the even positions of a list, you can use:

In [5]:
m[slice(0,5,2)]

[0, 2, 4]

which is equivalent to

In [6]:
m[0:5:2]

[0, 2, 4]

## EXERCISE: Slicing Review

In [8]:
# access the first five elements of the list
# YOUR CODE HERE
m[0:5]

[0, 1, 2, 3, 4]

In [13]:
# access the last five elements of the list
# YOUR CODE HERE
m[5:10]

[5, 6, 7, 8, 9]

In [10]:
# access the list elements in reverse order
# YOUR CODE HERE
m[-1:0:-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1]

## pylab mode

These imports done for you in `pylab` mode.

    import numpy as np
    import matplotlib.pyplot as plt
    
The same can be done with the following command:

In [14]:
%pylab inline


%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


# NumPy

<http://www.numpy.org/>:

NumPy is the **fundamental package for scientific computing with Python**. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (**broadcasting**) functions [what is *broadcasting*?]
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

### ndarray.ndim, ndarray.shape

In [15]:
# zero-dimensions

a0 = array(5)
a0

array(5)

In [16]:
a0.ndim, a0.shape

(0, ())

In [17]:
# 1-d array
a1 = array([1,2])
a1.ndim, a1.shape

(1, (2,))

In [18]:
# 2-d array
a2 = array(([1,2], [3,4]))
a2.ndim, a2.shape

(2, (2, 2))

In [19]:
a = arange(10)

In [20]:
a.dtype

dtype('int32')

### Array creation routines

In [21]:
a = array([1,2])
a

array([1, 2])

In [22]:
a = zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [23]:
a = ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [24]:
a = empty((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [25]:
a = eye(3,4,1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
a = identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
a = diag(arange(4))
a

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [28]:
a = linspace(1,10,5) 
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
a = logspace(1,2,5) 
a

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

###Type hierarchy: 

<img src="http://docs.scipy.org/doc/numpy/_images/dtype-hierarchy.png">

In [30]:
a = arange(10, dtype=float)
a.dtype

dtype('float64')

In [ ]:
a = arange(10, dtype=byte)
a.dtype

In [31]:
a[0] = 128
a[0]

128.0

In [32]:
a1 = a.astype(int16)
a1[0] = 128
a1[0]

128

### reshape, transpose

In [33]:
a = arange(64)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [34]:
# map a 0..63 1d array to a 8x8 2d array
a1 = a.reshape(8,8)
a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [35]:
a.shape = (8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [36]:
a.T

array([[ 0,  8, 16, 24, 32, 40, 48, 56],
       [ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63]])

### stacking & concatenation

In [37]:
a = array([[1, 2], [3, 4]])
b = array([[5, 6]])
print (a.shape, b.shape)

(2, 2) (1, 2)


In [38]:
x = concatenate((a, b), axis=0) # vertical stack
print (x, x.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [39]:
y = concatenate((a, b.T), axis=1) # horizontal
print (y, y.shape)

[[1 2 5]
 [3 4 6]] (2, 3)


In [40]:
print (vstack((a,b)))
print (hstack((a,b.T)))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [41]:
print (append(a, b, axis=0))
print (append(a, b.T, axis=1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [42]:
print (insert(a, 0, b, axis=0))
print (insert(a, 0, b, axis=1))

[[5 6]
 [1 2]
 [3 4]]
[[5 1 2]
 [6 3 4]]


# Numpy operations

example of [broadcasting](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html):

> The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

In [43]:
2*a

array([[2, 4],
       [6, 8]])

In [44]:
a+2

array([[3, 4],
       [5, 6]])

More broadcasting

<img src="http://scipy-lectures.github.io/_images/numpy_broadcasting.png" width="600">

In [45]:
a = array([range(0,3)]*4)
b = array([range(0,40,10)]*3).T
a, b

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30]]))

In [46]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [47]:
b + arange(0,3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [48]:
arange(0,40,10).reshape(4,1) + arange(0,3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [49]:
w = arange(0,3)
a = arange(0,12).reshape(4,3)
print (w)
print (a)
print (w * a)

[0 1 2]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]
 [ 0 10 22]]


## Indexing/Slicing

In [50]:
a3 = arange(30) 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
print (a3[0])
print (a3[::-1])
print (a3[2:5])

0
[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]
[2 3 4]


In [52]:
print (a3[[2,3,4,6,5,2]])

[2 3 4 6 5 2]


In [53]:
np.mod(a3, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2], dtype=int32)

Select numbers divisible by 3.

In [54]:
# list comprehension
[i for i in a3 if i % 3 == 0]

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [55]:
np.mod(a3, 3) == 0

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False])

In [56]:
divisible_by_3 = np.mod(a3, 3) == 0
a3[divisible_by_3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

2d, 3d slicing

In [57]:
a = arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [58]:
a[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [59]:
a[:,0]

array([ 0,  8, 16, 24, 32, 40, 48, 56])

In [60]:
a[:2,:2]

array([[0, 1],
       [8, 9]])

In [61]:
a[::2,::2]

array([[ 0,  2,  4,  6],
       [16, 18, 20, 22],
       [32, 34, 36, 38],
       [48, 50, 52, 54]])

In [62]:
b = arange(27).reshape(3,3,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [63]:
b[0,:,:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
b[:,0,:]

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])

In [65]:
b[:,:,0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

## Exercise:  Calculate a series that holds all the squares less than 100

In [67]:
# Use arange, np.sqrt, astype
# YOUR CODE HERE
n=100
square = 0.0

while square < n:
    square = square + 1
    print(square * square)

1.0
4.0
9.0
16.0
25.0
36.0
49.0
64.0
81.0
100.0
121.0
144.0
169.0
196.0
225.0
256.0
289.0
324.0
361.0
400.0
441.0
484.0
529.0
576.0
625.0
676.0
729.0
784.0
841.0
900.0
961.0
1024.0
1089.0
1156.0
1225.0
1296.0
1369.0
1444.0
1521.0
1600.0
1681.0
1764.0
1849.0
1936.0
2025.0
2116.0
2209.0
2304.0
2401.0
2500.0
2601.0
2704.0
2809.0
2916.0
3025.0
3136.0
3249.0
3364.0
3481.0
3600.0
3721.0
3844.0
3969.0
4096.0
4225.0
4356.0
4489.0
4624.0
4761.0
4900.0
5041.0
5184.0
5329.0
5476.0
5625.0
5776.0
5929.0
6084.0
6241.0
6400.0
6561.0
6724.0
6889.0
7056.0
7225.0
7396.0
7569.0
7744.0
7921.0
8100.0
8281.0
8464.0
8649.0
8836.0
9025.0
9216.0
9409.0
9604.0
9801.0
10000.0


# NumPy Functions

http://docs.scipy.org/doc/numpy/reference/routines.math.html

In [68]:
import random
a = array([random.randint(0, 10) for i in range(10)])

print (a)
print (a.min())
print (a.max())
print (a.mean())
print (a.std()) # standard deviation
print (a.sum())

[ 5  9  4  7  5  4  6  4 10  5]
4
10
5.9
2.022374841615669
59


In [69]:
b = arange(16).reshape(4, 4)
print (b)
print (b.T)
print (b.trace())
print (b.min())
print (b.min(axis=0))
print (b.min(axis=1))
print (b.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
30
0
[0 1 2 3]
[ 0  4  8 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [70]:
a = arange(0,3)
b = arange(1,4)
print (a, b)
print (np.dot(a,b))

[0 1 2] [1 2 3]
8


### Matrices

In [71]:
a = matrix([[3, 2, -1], [2, -2, 4], [-1, .5, -1]])
print (a)
print (a.trace())
print (a.diagonal())
print (a.T) # matrix transpose
print (a.I) # matrix inverse
print (a.H) # matrix conjugate transpose

[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]
[[0.]]
[[ 3. -2. -1.]]
[[ 3.   2.  -1. ]
 [ 2.  -2.   0.5]
 [-1.   4.  -1. ]]
[[ 0.         -0.5        -2.        ]
 [ 0.66666667  1.33333333  4.66666667]
 [ 0.33333333  1.16666667  3.33333333]]
[[ 3.   2.  -1. ]
 [ 2.  -2.   0.5]
 [-1.   4.  -1. ]]


In [73]:
a = matrix(arange(0,6).reshape(2,3))
print (a.T * a) #it's ok to have an error, we need to use the transpose matrix!

[[ 9 12 15]
 [12 17 22]
 [15 22 29]]


In [74]:
print (a * a.T)

[[ 5 14]
 [14 50]]


## Exercise: Implement the matrix product using python loops and compare the execution time with the Numpy implementation

In [ ]:
a = arange(50).reshape(5,10)

def my_dot(a,b):
    
    for i in range(a.shape[0]):
        
    
    # YOUR CODE HERE

In [ ]:
%timeit my_dot(a,a.T)

In [ ]:
%timeit a*a.T

## Exercise:  Reimplement the perceptron using NumPy (e.g., using the matrix product operation)

In [ ]:
%%file data.csv
x1,x2,y
0.4946,5.7661,0
4.7206,5.7661,1
1.2888,5.3433,0
4.2898,5.3433,1
1.4293,4.5592,0
4.2286,4.5592,1
1.1921,5.8563,0
3.1454,5.8563,1
1.063,5.7357,0
5.1043,5.7357,1
1.5079,5.8622,0
3.9799,5.8622,1
0.2678,6.9931,0
4.5288,6.9931,1
0.9726,3.6268,0
4.106,3.6268,1
2.5389,3.3884,0
4.7555,3.3884,1
2.473,5.6404,0
4.7977,5.6404,1

In [ ]:
data = np.genfromtxt('data.csv', delimiter=',', skip_header=1)

X = data[:,:-1]
y = data[:,-1]

print (X)
print (y)

In [ ]:
c0 = y==0
c1 = y==1

plot(X[:,0][c0], X[:,1][c0], 'o', mec='r', mfc='none')
plot(X[:,0][c1], X[:,1][c1], 'o', mec='g', mfc='none')

In [ ]:
class Perceptron:
        
    def predict(self, x):
        # YOUR CODE HERE

    def fit(self, X, y):
        self.w = zeros(len(x))
        # YOUR CODE HERE, using dot product

p = Perceptron()
p.fit(X, y)

for i,x in enumerate(X):
    if p.predict(x) != y[i]:
        print 'FAIL'
        break
else:
    print 'SUCCESS!'

## Exercise:  Read a digits image and split it up in different training examples

In [ ]:
from scipy import misc
img = misc.imread('digits.png', flatten=1)

print (img.shape)
print (img.dtype)

imshow(img, cmap=cm.Greys_r)

In [ ]:
data = []

# YOUR CODE HERE

In [ ]:
print (data[20])
imshow(data[20], cmap=cm.Greys_r)

# Random Generators

In [ ]:
from numpy import random
data = random.normal(size=1000, loc=2)
h=plt.hist(data, bins=50)

http://docs.scipy.org/doc/numpy/reference/routines.random.html

In [ ]:
from numpy import random
data = random.exponential(size=1000)
h = plt.hist(data, bins=50)

## Exercise:  Create a set of 100 points that follow the function $$f(x) = 0.5x + 1 $$ and add Gaussian white noise to the result. 

In [ ]:
X = linspace(1,10,100)

# YOUR CODE HERE

## Exercise: Use polinomial fitting (numpy.polyfit) to fit the results in a line and verify that the error is Gaussian white noise.

In [ ]:
c = polyfit(X, y, 1)

# YOUR CODE HERE

#Linear Regression

##Exercise: Linear Regression with Ordinary Least Squares

Find the weight values $\mathbf{w}$ that minimize the error $E_{\mathbf{in}}(\mathbf{w}) = \frac{1}{N} \sum_{n=1}^n {(\mathbf{w}^T \mathbf{X}_n - \mathbf{y}_n)^2}$.

For this, implement Linear Regression and use the Ordinary Least Squares (OLS) closed-form expression to find the estimated values of $\mathbf{w}$:

$$\mathbf{w} = (\mathbf{X}^{\rm T}\mathbf{X})^{-1} \mathbf{X}^{\rm T}\mathbf{y}$$

You can use the `np.linalg.inv` function to invert a matrix:

In [ ]:
help(np.linalg.inv)

The following function generates some data to test the linear regression:

In [ ]:
def generate_linear_regression(c):
    X = np.random.rand(100, len(c)-1)
    noise = random.normal(size=len(X), loc=0, scale=0.1)
    y = ((c[0] + X*c[1:]).sum(axis=1) + noise).reshape(100, 1)
    
    return X, y

X, y = generate_linear_regression([2, 0.8])
scatter(X, y)

To implement the linear regression, follow these steps:

1. extend $\mathbf{X}$ to $d + 1$ dimensions, setting the first column to 1
2. calculate $\mathbf{w}$ using the OLS closed form

In [ ]:
# YOUR CODE HERE

##Exercise: Linear Regression with nonlinear data

Even if the data is nonlinear, linear regression can be used. 
The first step is to transform the data nonlinearly and append it as new features.

The following function creates nonlinear data:

In [ ]:
def generate_linear_regression_squared(c):
    X = np.random.rand(100, len(c)-1)
    noise = random.normal(size=len(X), loc=0, scale=0.1)
    y = ((c[0] + c[1:]*X**2).sum(axis=1) + noise).reshape(100, 1)
    
    return X, y

X, y = generate_linear_regression_squared([2, 2])
scatter(X, y)

To apply the linear regression in nonlinear data, follow these steps:

1. extend $\mathbf{X}$ to add a nonlinear transformation of $\mathbf{X}$ (e.g., $\mathbf{Z} = [\mathbf{X}, \mathbf{X}^2$]).
1. extend $\mathbf{Z}$ to $d + 1$ dimensions, setting the first column to 1.
2. calculate $\mathbf{w}$ applying OLS to $\mathbf{Z}$.

In [ ]:
# YOUR CODE HERE